### ISSUE TITLE
Fix `livenow` label under only courses that are live

### ISSUE THREAD

**Issue by Anishyou** [TUM-Dev/gocast_mobile#101]

**Comment by GravityDarkLab** [comment]
- This fix needs to wait till we have the `streamHandlers` in the Flutter client

**Comment by ahmetsenturk** [comment]
Then please move it to the blocked column

**Comment by carlobortolan** [comment]
> Then please move it to the blocked column

By now the `StreamHandler` has already been implemented (see #)
