### ISSUE TITLE
Improve My courses and public courses view UI

### ISSUE THREAD

**Issue by Anishyou** [TUM-Dev/gocast_mobile#102]
There is too much whitespace.
May be think of something what can we do

**Comment by milenark** [comment]
Important things are: 

- [ ] fix the whitespace
- [ ] make the title (largely) visible
- [ ] display course number instead of slug
- [ ] align live button to figma design
- [ ] remove blue background tint

**Comment by milenark** [comment]
Current progress: 
![Image](https://github.com/TUM-Dev/gocast_mobile/assets/84514915/df28c601-040b-4b08-86eb-54a434ef2619)

**Comment by carlobortolan** [comment]
Looks great :+1: 
Just two things I'd note: 
1. The "live now" section doesn't actually show the courses, but rather streams that are currently live (as one course could have multiple live streams at once). So when clicking on a item in "live now", it should go directly to the stream/video.
2. The API returns also some information such as what the LastRecording and NextLecture for a given course will be (with a link to the stream) (e.g., see tumlive web app). So if you want / if it fits in the cards, you can also add that.
