### ISSUE TITLE
Fix padding on downloads and pinned screen for title

### ISSUE THREAD

**Issue by Anishyou** [TUM-Dev/gocast_mobile#113]
The title is so much on corner. Fix the padding, put it on center or give some space for it.
Do not change the other title for home and notifications

**Comment by cbetul** [comment]
Hi, I just fixed this issue in here https://github.com/TUM-Dev/gocast_mobile/issues/122
For the pinned courses, I'll fix the padding on this issue https://github.com/TUM-Dev/gocast_mobile/issues/97
So, I think we can just close this one.
