### ISSUE TITLE
Create new home design

### ISSUE THREAD

**Issue by milenark** [TUM-Dev/gocast_mobile#134]
### Objective
Create a few prototypes for displaying the courses on the home screen that are more aligned to the current tumlive view and less reliant on a thumb nail, code the best one in our flutter project. 

### Progress: 
- [x] sketches created
- [x] code written
#### More specific: 
- [x] fix livenow for courses
- [x] livestreams redirect to video player
- [x] display viwercount
- [x] display roomname, redirect to navigaTUM
- [x] display last lecture
- [x] add pulsing LiveNow as on tumlive
- [x] display colored stirp based on fachschaft (eg. blue for **IN**0009)
- [x] make compatible with darkmode
- [x] make listview compatible with new cards
- [x] clean up code of new components
- [x] make compatible with table view
- [x] add null- and exception checks for edge cases (eg. for extra long titles, unset fields) 
- [x] add navigation to course detail view
- [ ] incorporate Benedicts feedback

### Impediment: 
course.streams is somehow always empty

### TumLive view: 
<img width="300" alt="Screenshot 2024-01-04 at 17 11 40" src="https://github.com/TUM-Dev/gocast_mobile/assets/84514915/c63729b2-6511-4c64-9fa7-0df70f288c0c">

### Home: 
<img width="300" alt="Screenshot 2024-01-14 at 16 59 13" src="https://github.com/TUM-Dev/gocast_mobile/assets/84514915/d9c76392-14d4-4a05-a107-9799201e35fc">

<img width="450" alt="Screenshot 2024-01-14 at 16 59 13" src="https://github.com/TUM-Dev/gocast_mobile/assets/84514915/ba08f363-6a66-410e-81ba-858615c65504">

#### Course Detail View: 
<img width="300" alt="Screenshot 2024-01-21 at 17 47 59" src="https://github.com/TUM-Dev/gocast_mobile/assets/84514915/d33f9d90-bf9d-4c0a-9b2e-3f725446b1bb">

<img width="300" alt="Screenshot 2024-01-21 at 17 48 39" src="https://github.com/TUM-Dev/gocast_mobile/assets/84514915/3a518830-ee15-4cfb-923a-7ed92cf23160">

**Comment by ahmetsenturk** [comment]
I like the current ideas and how you incorporated the viewer count as well - great job! 😊
