### ISSUE TITLE
implement-course-view

### ISSUE THREAD

**Issue by Sainaamr** [TUM-Dev/gocast_mobile#136]
### Description

- [x] create the UI
- [x]  write the handlers
- [x] connect the ui to the backend
- [x] a search bar at the top with a filter next to it
- [x] title of the course
- [x] an array of the  thumbnails of streams with the title bellow it

### Expected Results
- [x] a functioning course view

**Comment by carlobortolan** [comment]
Related gRPC methods:
- [getCourseStreams](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/657478f6bbd4b43e3f7314ed) - returns all streams (live&VoD) for a given course
- [getThumbsVOD](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/656f3908388ab1b37e908005) - returns thumbnail for a Vod (`live_now == false`)
- [getThumsLive](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/656f4125388ab1b37e9091e7) - returns thumbnail for a live stream (`live_now == true`)
