### ISSUE TITLE
Implement User Settings View UI

### ISSUE THREAD

**Issue by cbetul** [TUM-Dev/gocast_mobile#140]
### Objective

Design and implement the User Settings View UI. Ensure accessibility and responsiveness across various devices.

##
Related issue:
#48

**Comment by ahmetsenturk** [comment]
The same settings as the TUM-live application
<img width="813" alt="Screenshot 2023-12-22 at 10 28 17" src="https://github.com/TUM-Dev/gocast_mobile/assets/35606355/7b29d305-5675-44bf-9a54-ae0fe3bec277">
