### ISSUE TITLE
Give an option for different camera views to be able to download

### ISSUE THREAD

**Issue by Anishyou** [TUM-Dev/gocast_mobile#226]

**Comment by GravityDarkLab** [comment]
This is not important :)
Also i remember that the server only provide 1 video which is the combined one (playListURL one)

**Comment by Anishyou** [comment]
Actually we get three
e.g.
 "Downloads": [
    {
      "FriendlyName": "Combined",
      "DownloadURL": "https://edge.live.rbg.tum.de/vod/170/5133/COMB/playlist.m3u8?jwt=<YOUR-PRIVATE-TOKEN-WOULD-BE-HERE>&download=1"
    },
    {
      "FriendlyName": "Camera",
      "DownloadURL": "https://edge.live.rbg.tum.de/vod/170/5133/CAM/playlist.m3u8?jwt=<YOUR-PRIVATE-TOKEN-WOULD-BE-HERE>&download=1"
    },
    {
      "FriendlyName": "Presentation",
      "DownloadURL": "https://edge.live.rbg.tum.de/vod/170/5133/PRES/playlist.m3u8?jwt=<YOUR-PRIVATE-TOKEN-WOULD-BE-HERE>&download=1"
    }
  ],

**Comment by GravityDarkLab** [comment]
Ah ok, that s now included in the normal API then
