### ISSUE TITLE
[CAT]No Memoji  at the team intro page. - Rest of the presentation no problem.

### ISSUE THREAD

**Issue by Anishyou** [TUM-Dev/gocast_mobile#269]

**Comment by mo-cmyk** [comment]
Please all do this on your own and add a normal picture of yourself to this slide

- [ ] Milena
- [ ] Saina
- [ ] Ahraf
- [ ] Carlo
- [ ] Anish
- [x] Moritz
- [x] Robert
- [x] Ahmet
