### ISSUE TITLE
Make `notification_view.dart` receive updates

### ISSUE THREAD

**Issue by GravityDarkLab** [TUM-Dev/gocast_mobile#47]
fetch notifications from API

**Comment by ahmetsenturk** [comment]
Could you provide some description of what this task is about?

**Comment by carlobortolan** [comment]
@GravityDarkLab  @milenark 
For the notifications,`notification_view.dart` only has to fetch the server notifications (= `BannerAlerts` and `FeatureNotifications`) from the api, as the push-notifications are already handled [here](https://github.com/TUM-Dev/gocast_mobile/issues/73) and don't need to be fetched.
