### ISSUE TITLE
Implement Bookmarks

### ISSUE THREAD

**Issue by GravityDarkLab** [TUM-Dev/gocast_mobile#52]
- [ ] Bookmark UI: When watching a stream, display a button to save a timestamp
- [ ] API Calls: Save the timestamp
- [ ] List view: See all saved timestamps

**Comment by ahmetsenturk** [comment]
What is this, a view? Please provide some more details here.

**Comment by GravityDarkLab** [comment]
My bad, this is should be a user story.
Also we might not implement it as we though that bookmarks = pinned but it is not the case

**Comment by milenark** [comment]
- [ ] Bookmark UI: When watching a stream, display a button to save a timestamp
- [ ] API Calls: Save the timestamp
- [ ] List view: See all saved timestamps

**Comment by ahmetsenturk** [comment]
Since bookmarks=pinned this user story is completed.
