### ISSUE TITLE
Collect ideas and presentation plans

### ISSUE THREAD

**Issue by GravityDarkLab** [TUM-Dev/gocast_mobile#58]
Gather ideas from everyone about our DR structure and present them in the next team meeting.

-  previous [DRs](https://ase.cit.tum.de/projects/ipraktikum/)

**Comment by Sainaamr** [comment]
https://docs.google.com/presentation/d/1I-zGsywmpujk15-aXhPmDfjjv_LExRydnoIf1GcQf3E/edit?usp=sharing
