### ISSUE TITLE
Tests for the different API's Endpoint

### ISSUE THREAD

**Issue by GravityDarkLab** [TUM-Dev/gocast_mobile#65]
**As a** client,
**I want** that the API is tested,
**So that** I can assure that the provided endpoints behave as intended.

**Comment by carlobortolan** [comment]
Postman collection should be sufficient for now.

**Comment by ahmetsenturk** [comment]
So, somebody is working on this? It's in progress without an assignee and no sprint.

**Comment by carlobortolan** [comment]
> So, somebody is working on this? It's in progress without an assignee and no sprint.

Should still be a "TODO" as we don't plan to write any tests this sprint. (Will start probably next sprint)

**Comment by ahmetsenturk** [comment]
Is this related to #62 ?

**Comment by carlobortolan** [comment]
> Is this related to #62 ?

This should be a user story linked to the epic #62
