### ISSUE TITLE
[Design Review] Subsystem Decomposition

### ISSUE THREAD

**Issue by GravityDarkLab** [TUM-Dev/gocast_mobile#78]
Current draft for the iconised subsystem decomposition:
![image](https://github.com/TUM-Dev/gocast_mobile/assets/106114526/fee6263b-e0f4-4729-b538-3ca341eaf170)

Final version:
![image](https://github.com/TUM-Dev/gocast_mobile/assets/106114526/f8d38f75-eb5f-4e79-8a77-1608c22a64c4)

**Comment by carlobortolan** [comment]
![image](https://github.com/TUM-Dev/gocast_mobile/assets/106114526/b4352b10-a432-49b9-8569-6481dc6c5281)
