### ISSUE TITLE
Revisit AOM

### ISSUE THREAD

**Issue by ahmetsenturk** [TUM-Dev/gocast_mobile#9]

**Comment by ahmetsenturk** [comment]
![Image](https://github.com/TUM-Dev/gocast_mobile/assets/35606355/3a2f644a-2a93-41ce-a60e-0ddb9c6c13dd)

**Comment by mo-cmyk** [comment]
![ClassDiagram](https://github.com/TUM-Dev/gocast_mobile/assets/58398080/c46b25c7-6285-4c8c-ae55-c15f84f2b0d2)
