### ISSUE TITLE
Implement chat view UI

### ISSUE THREAD

**Issue by Anishyou** [TUM-Dev/gocast_mobile#96]

**Comment by ahmetsenturk** [comment]
I belive this should not be done in sprint 3, right?

**Comment by Anishyou** [comment]
This is to have just UI not the functionality. I plan to start it after finishing with navigation. It is highky possible I do it this week

**Comment by carlobortolan** [comment]
# Relevant endpoints for this issue:

## Main Message related:
- [getChatMessages](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596dccf5188ca95c7b7e790)
- [postChatMessages](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596ddad15ac68cb19987f65)
- [postChatReply](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596e63415ac68cb19988d74)

## Reaction related:
- [postChatReaction](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596de2d5188ca95c7b7ea34)
- [deleteChatReaction](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596df3215ac68cb199881b3)

## Admin-related (not sure if we need these in the client...)
- [markChatResolved](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596e8c815ac68cb1998918c)
- [markChatUnresolved](https://www.postman.com/tumdev/workspace/team-workspace/grpc-request/6596e92515ac68cb19989219)
